function help_info()
{
	echo "NAME"
	echo "    auto-send.sh automatically send microblog(weibo) in linux"
	echo "USAGE"
	echo "    ./auto-send.sh [-f|-c  |\"content\"] [ -p /path/to/pic.png]"
	echo "OPTIONS"
	echo "    -h       this help manual."
	echo "    -f       send file './weibo/weibo.cont' content"
	echo "    -c       [contents], short content text information"
#	echo "    -l       images list, all images are stored in ./images/"
	echo "    -p       image path default:./images/weibo.png"
	echo "EXAMPLE"
	echo "     ./auto-send.sh -c \"My first test microblog \" "
	echo "     ./auto-send.sh -f "
#   echo "     ./auto-send.sh -l images.list -c \"My Raspberry Pi\""
	echo "     ./auto-send.sh -p ./images/pi.png -f"
	echo "NOTE"
	echo "     This version only support single picture"
	echo "AUTHOR"
	echo "     Aborn Jiang (loveaborn@foxmail.com)"
	echo "VERSION"
	echo "     v0.1  2013-10-02"
}
